# Generated by Django 4.1.1 on 2022-10-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_id', models.CharField(max_length=20)),
                ('pro_name', models.CharField(max_length=100)),
                ('pro_price', models.CharField(max_length=10)),
                ('pro_quantity', models.CharField(max_length=5)),
                ('pro_image', models.ImageField(upload_to='products')),
            ],
        ),
    ]
