# Generated by Django 4.1.1 on 2022-11-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_products_pro_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='pro_image',
            field=models.ImageField(upload_to='products1'),
        ),
    ]
