# Generated by Django 4.1.1 on 2022-11-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_products_pro_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='pro_image',
            field=models.ImageField(upload_to='products'),
        ),
    ]
