# Generated by Django 4.1.1 on 2022-11-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doct_name', models.CharField(max_length=100)),
                ('doc_spec', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
